### PR TITLE
[wip] collect preview headers

### PR DESCRIPTION
**Pull request by zeke**
Hey @gr2m this is a start. What next?

### CODE REVIEW

**Comment by gr2m** [comment]
I would remove the duplicated preview headers from the array. 

What would be cool to add

1. Map preview header to routes it applies to, e.g.  
   
   ```json
   {
     "application/vnd.github.drax-preview+json": [
       "GET /licenses", 
       "GET /licenses/:license", 
       "GET /repos/:owner/:repo", 
       "GET /repos/:owner/:repo/license"
     ],
     ...
   }
   ```

2. Map routes to preview headers
   
   ```json
   {
     "GET /licenses": ["application/vnd.github.drax-preview+json"],
     ...
   }
   ```

What do you think?

**Comment by zeke** [comment]
That sounds good. I don't have a use case for this just now, so I may not get to it right away. Feel free to take this on if you need it soon. :)

**Comment by zeke** [comment]
@gr2m is this still needed? Or is there another project out there now that solves this?

**Comment by gr2m** [comment]
it would be a nice addition to octokit/routes, but it's not there yet

**Pull request closed without merging**
